import { execFileSync } from "node:child_process";
import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { PackageManagerKind } from "../stacks.js";

export class HooksConflictError extends Error {
  constructor(existing: string) {
    super(
      `qa: core.hooksPath is already set to '${existing}' (for example Husky).\n` +
        `To use @develoz/quality-assurance hooks, remove the other hook manager and re-run 'qa hooks install'.`
    );
    this.name = "HooksConflictError";
  }
}

export class NotAGitRepositoryError extends Error {
  constructor(cwd: string) {
    super(`qa: '${cwd}' is not a git repository.`);
    this.name = "NotAGitRepositoryError";
  }
}

export interface HooksInstallResult {
  hookPath: string;
  hooksPath: string;
  /** Whether the hook file content changed on this run. */
  changed: boolean;
}

const HOOKS_PATH = ".githooks";
const HOOK_FILE = "pre-commit";

function qaCommand(packageManager: PackageManagerKind): string {
  switch (packageManager) {
    case "pnpm":
      return "pnpm exec qa";
    case "bun":
      return "bun x qa";
    default:
      return "npx --no-install qa";
  }
}

/**
 * Pre-commit hook: staged lint and format, then a full typecheck when any
 * TypeScript is staged. The typecheck is never given a file list because `tsc`
 * ignores tsconfig.json when handed explicit files.
 */
export function renderPreCommitScript(packageManager: PackageManagerKind): string {
  const qa = qaCommand(packageManager);
  return `#!/bin/sh
# Generated by @develoz/quality-assurance. Managed file; re-run \`qa hooks install\`.
set -eu

QA="${qa}"

# shellcheck disable=SC2086
$QA pre-commit || {
  printf 'qa: pre-commit failed. Bypass with: git commit --no-verify\\n' >&2
  exit 1
}
`;
}

function git(cwd: string, args: string[]): { ok: boolean; stdout: string } {
  try {
    const stdout = execFileSync("git", args, {
      cwd,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    });
    return { ok: true, stdout };
  } catch {
    return { ok: false, stdout: "" };
  }
}

function currentHooksPath(cwd: string): string | null {
  const result = git(cwd, ["config", "--get", "core.hooksPath"]);
  const value = result.stdout.trim();
  return result.ok && value.length > 0 ? value : null;
}

export function installHooks(cwd: string, packageManager: PackageManagerKind): HooksInstallResult {
  if (!git(cwd, ["rev-parse", "--git-dir"]).ok) {
    throw new NotAGitRepositoryError(cwd);
  }

  const existing = currentHooksPath(cwd);
  if (existing !== null && existing !== HOOKS_PATH) {
    throw new HooksConflictError(existing);
  }

  const dir = join(cwd, HOOKS_PATH);
  mkdirSync(dir, { recursive: true });
  const hookPath = join(dir, HOOK_FILE);
  const content = renderPreCommitScript(packageManager);
  const changed = !existsSync(hookPath) || readFileSync(hookPath, "utf8") !== content;

  if (changed) {
    writeFileSync(hookPath, content, "utf8");
  }
  chmodSync(hookPath, 0o755);

  git(cwd, ["config", "core.hooksPath", HOOKS_PATH]);

  return { hookPath, hooksPath: HOOKS_PATH, changed };
}
